default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bokriumm_development


test:
  <<: *default
  database: bokriumm_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

