name: Setup Ruby environment
description: Checkout and Ruby setup with bundler cache (for lint/audit jobs)

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
